"""
Detection et suppression des metadonnees de provenance IA (C2PA, tags
"AI-generated"...) dans la video finale.

Port Python de la logique d'inspection/strip de
github.com/yvongate/remove-ai-matadata (back/src/videos/metadata.inspector.ts,
meme auteur). Reecrit ici en stdlib pur (pas de dependance pip) pour rester
dans l'esprit du pipeline Ferdinand : generate.py n'a aujourd'hui aucune
dependance Python externe, juste ffmpeg/ffprobe en sous-process.

Ce module ne touche QUE le conteneur (tags, boites MP4) : rapide, gratuit,
sans reencodage (`-c copy`). Il ne touche pas aux pixels - voir
synthid_remove.py pour la regeneration VAE (optionnelle, couteuse, et sans
rapport avec Runway/Seedance qui ne portent pas de filigrane SynthID).
"""

from __future__ import annotations

import json
import re
import struct
import subprocess
from pathlib import Path

STRONG_MARKERS = [
    "c2pa",
    "jumb",
    "contentcredentials",
    "trainedalgorithmicmedia",
    "compositesynthetic",
    "aigc",
    "ai generated",
    "ai-generated",
    "generated by ai",
    "digitalsourcetype",
    "synthid",
]

# Couvre deja runway et seedance (les deux modeles de ce pipeline), plus les
# autres generateurs qu'un montage externe pourrait introduire.
GENERATOR_RE = re.compile(
    r"\b(sora|veo|kling|seedance|doubao|jimeng|hailuo|minimax|runway|gen-?[34]|"
    r"pika|luma|dream machine|midjourney|dall-?e|openai|firefly|gemini|imagen|"
    r"stable ?video|wan2|vidu|pixverse|haiper|ai[- ]generated|artificial intelligence)\b",
    re.IGNORECASE,
)

MP4_EXT = re.compile(r"\.(mp4|m4v|mov)$", re.IGNORECASE)
META_BOXES = {"uuid", "udta", "meta", "jumb", "xml ", "XMP_", "cprt", "ilst", "keys"}
# Boites qui ne contiennent que d'autres boites : on descend dedans.
CONTAINER_BOXES = {"moov", "trak", "mdia", "minf", "stbl", "edts", "dinf", "udta", "moof", "traf"}
SKIP_BOXES = {"mdat", "free", "skip", "wide"}
SCAN_CHUNK = 4 * 1024 * 1024
MAX_MARKER_LEN = 32
RAW_SCAN = 2 * 1024 * 1024


def _ffprobe_json(path: Path) -> dict:
    try:
        out = subprocess.run(
            ["ffprobe", "-v", "error", "-print_format", "json",
             "-show_format", "-show_streams", "-show_chapters", str(path)],
            capture_output=True, text=True, check=False,
        ).stdout
        return json.loads(out) if out else {}
    except (OSError, json.JSONDecodeError):
        return {}


def _collect_tags(probe: dict) -> dict:
    tags: dict[str, str] = {}
    for k, v in (probe.get("format", {}).get("tags") or {}).items():
        tags[f"format.{k}"] = str(v)
    for i, s in enumerate(probe.get("streams") or []):
        for k, v in (s.get("tags") or {}).items():
            tags[f"stream{i}.{k}"] = str(v)
    for i, c in enumerate(probe.get("chapters") or []):
        for k, v in (c.get("tags") or {}).items():
            tags[f"chapter{i}.{k}"] = str(v)
    return tags


def _strong_markers_in(buf: bytes, found: set[str]) -> None:
    text = buf.decode("latin1", errors="ignore").lower()
    for m in STRONG_MARKERS:
        if m in text:
            found.add(m)


def _scan_range(f, pos: int, length: int, markers: set[str]) -> None:
    """Cherche les marqueurs dans [pos, pos+length) par blocs, sans limite de
    taille de boite. Chevauchement de MAX_MARKER_LEN octets entre blocs."""
    done = 0
    while done < length:
        want = min(SCAN_CHUNK + MAX_MARKER_LEN, length - done)
        f.seek(pos + done)
        chunk = f.read(want)
        if not chunk:
            break
        _strong_markers_in(chunk, markers)
        done += SCAN_CHUNK


def _walk_boxes(f, start: int, end: int, boxes: set[str], markers: set[str], depth: int = 0) -> None:
    pos = start
    while pos + 8 <= end and depth < 8:
        f.seek(pos)
        head = f.read(16)
        if len(head) < 8:
            break
        box_size = struct.unpack(">I", head[0:4])[0]
        box_type = head[4:8].decode("latin1", errors="ignore")
        header_len = 8
        if box_size == 1:
            if len(head) < 16:
                break
            box_size = struct.unpack(">Q", head[8:16])[0]
            header_len = 16
        elif box_size == 0:
            box_size = end - pos
        if box_size < header_len or pos + box_size > end:
            break

        if box_type in META_BOXES:
            boxes.add(box_type)

        if box_type == "meta":
            # "full box" : 4 octets version/flags avant les boites enfants
            _walk_boxes(f, pos + header_len + 4, pos + box_size, boxes, markers, depth + 1)
        elif box_type in CONTAINER_BOXES:
            _walk_boxes(f, pos + header_len, pos + box_size, boxes, markers, depth + 1)
        elif box_type not in SKIP_BOXES:
            _scan_range(f, pos, box_size, markers)
        pos += box_size


def _scan_mp4(path: Path, boxes: set[str], markers: set[str]) -> None:
    with open(path, "rb") as f:
        f.seek(0, 2)
        size = f.tell()
        _walk_boxes(f, 0, size, boxes, markers)


def _scan_raw(path: Path, markers: set[str]) -> None:
    with open(path, "rb") as f:
        f.seek(0, 2)
        size = f.tell()
        n = min(RAW_SCAN, size)
        f.seek(0)
        _strong_markers_in(f.read(n), markers)
        if size > n:
            f.seek(size - n)
            _strong_markers_in(f.read(n), markers)


def inspect_video(path) -> dict:
    """Analyse une video : tags ffprobe + scan des boites MP4, a la recherche
    de marqueurs de provenance IA (C2PA, tags de generateur, SynthID)."""
    path = Path(path)
    probe = _ffprobe_json(path)
    tags = _collect_tags(probe)
    boxes: set[str] = set()
    markers: set[str] = set()

    if MP4_EXT.search(path.name):
        _scan_mp4(path, boxes, markers)
    else:
        _scan_raw(path, markers)

    for k, v in tags.items():
        if GENERATOR_RE.search(v) or GENERATOR_RE.search(k):
            markers.add(f"tag:{k}")
        _strong_markers_in(f"{k} {v}".encode("latin1", errors="ignore"), markers)

    return {
        "container": (probe.get("format") or {}).get("format_name", "inconnu"),
        "tags": tags,
        "boxes": sorted(boxes),
        "markers": sorted(markers),
        "has_ai_metadata": len(markers) > 0,
    }


def strip_metadata(input_path, output_path) -> bool:
    """Retire toutes les metadonnees (tags, chapitres, C2PA) sans reencoder -
    rapide, pixels intacts. False si ffmpeg echoue ou est absent (non
    bloquant : l'appelant garde alors la video d'origine)."""
    args = [
        "ffmpeg", "-y", "-v", "error",
        "-i", str(input_path),
        "-map", "0", "-c", "copy",
        "-map_metadata", "-1",
        "-map_metadata:s:v", "-1",
        "-map_metadata:s:a", "-1",
        "-map_chapters", "-1",
        "-fflags", "+bitexact",
        "-flags:v", "+bitexact",
        "-flags:a", "+bitexact",
        "-movflags", "+faststart",
        str(output_path),
    ]
    try:
        result = subprocess.run(args, check=False)
    except OSError:
        return False
    return result.returncode == 0 and Path(output_path).exists()
